### ISSUE TITLE
specifying adult or larva for Lepidoptera prey

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#102]
@pwinner1 Can we double check all records where Prey_Order == Lepidoptera and Prey_Stage is blank or NA?

Ideally we'd like to distinguish between adult and larva, so take a look back at the original source to see if you can infer which is represented. In a few cases, I expect that there will be no clues, but often I think it was just left out in data entry.

Note that aerial foragers (e.g. Mississippi Kite, Black Swift, Common Nighthawk, Aplomado Falcon) are presumably feeding on adults.

Foliage gleaners (e.g. warblers, vireos, orioles, sparrows) are presumably feeding on larvae, although they might occasionally take adults.

Flycatchers are presumably feeding mostly on adults but occasionally take larvae.

**Comment by pwinner1** [comment]
Finished specifying Prey_Stage for blank Lepidoptera entries. Some I could not make a judgement as to which stage the author was referring to, in which case they were left blank.
