### ISSUE TITLE
clarify "Arachnida" prey, ITIS 82708

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#105]
Need to double check all records with "Prey_Name_ITIS_ID" == 82708, which corresponds to the Class Arachnida. In many cases, these records actually refer to "spiders" (which should specifiy Order Araneae, TSN 82732) or "mites" (Subclass Acari, TSN 733321).

Since we don't keep track of Subclass in this database, the Prey_Name_ITIS_ID should be filled in manually for "mite", and Prey_Common_Name should be filled in with "mites".

**Comment by ahhurlbert** [comment]
All records where Prey_Common_Name was specified so we could distinguish mites from spiders have been corrected. 

It would be good for someone to check the original sources for all remaining records with Prey_Name_ITIS_ID == 82708 in case it is possible to distinguish them.

**Comment by georgeni2442** [comment]
Finished clarifying records of "Arachnida" prey from original sources, was not able to check "Weigand, J. P. 1980. Ecology of the Hungarian Partridge in north-central Montana. Wildl. Monogr. 74:1-106.", as it was not available in the Papers with data folder.

**Comment by ahhurlbert** [comment]
Google search!

https://www.jstor.org/stable/pdf/3830707.pdf
