### ISSUE TITLE
add data from Passmore 1981

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#106]
Common Ground Dove data from Table 5 has already been entered (broken down by year), but Mourning Dove and White-winged Dove data in Tables 7 (spring), 8 (summer), and 9 (fall) need to be entered.

Also consider entering Common Ground Dove data from Tables 6-9 as well and deleting Table 5 data from the database which is the same data but averaged across seasons (and broken down by year). More useful probably to average over years and break down by season.

**Comment by georgeni2442** [comment]
Deleted Table 5 from AvianDietDatabase, entered in Tables 6-9 too.
