### ISSUE TITLE
add data from Errington and Breckenridge 1938

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#107]
Data for Broad-winged Hawk has already been entered, but additionally data exist for Rough-legged Hawk, Red-tailed Hawk, Red-shouldered Hawk, Swainson's Hawk.

Might want to verify that these data were not entered via other Errington references, but at least for Rough-legged this is not the case.

**Comment by georgeni2442** [comment]
Added data for Red-tailed, Rough-legged hawk, and Swainson's hawk, and verified existing data for broad-winged hawk.
