### ISSUE TITLE
woodpecker diet entries

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#12]
@jsbarnes Koplin & Baldwin 1970. There are two listings for American three-toed woodpecker and Hairy woodpecker for the same prey item (spruce beetle), but each row has different values. Can you clarify in the Notes field what the difference is between these rows? Also, the study calculated the % of diet of spruce beetle, but not of any other diet items? Double check and clarify this in the Notes field as well if necessary

**Comment by jsbarnes** [comment]
Fixed issue, clarified difference between entries as being during outbreak or non-outbreak years for spruce beetles.
