### ISSUE TITLE
add data from Wetmore 1916

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#123]
Wetmore 1916. Birds of Porto Rico. USDA Bulletin No. 326

Add quantitative diet data (often both % occurrence AND % by Wt_or_Vol) for all species in this publication where available, including Puerto Rican/Caribbean endemics and non-landbirds.

Note that a few species have already been entered in the existing file AvianDietDatabase_Wetmore_1916_CB.txt

**Comment by jfox590** [comment]
Data for Wetmore 1916 added to Dietdatabase
