### ISSUE TITLE
Brown-crested flycatcher diet data source?

### ISSUE THREAD

**Issue by msandova** [hurlbertlab/dietdatabase#13]
@mauriemma do you remember where you found the source for the "Rosenberg, K. V., R. D. Ohmart, W. C. Hunter, and B. W. Anderson.?1991.Birds of the lower Colorado River Valley.?Univ. of Arizona Press, Tucson" information for the brown-crested flycatcher species.I'm having trouble finding it to save it as a pdf to the server.

**Comment by mauriemma** [comment]
To be honest, I don't remember how I found this source.  I'll keep trying to look, but couldn't find access to it again.  Will let you know if I do find it

**Comment by ahhurlbert** [comment]
I'm guessing that the data presented in this source originally came from this earlier work by the same authors, which we are in the process of entering.

Rosenberg, K. V., R. D. Ohmart, and B. W. Anderson. 1982. Community organization of riparian breeding birds: response to an annual resource peak. Auk 99:260-274.
