### ISSUE TITLE
Golden eagle diet data

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#134]
https://onlinelibrary-wiley-com.libproxy.lib.unc.edu/doi/10.1111/ibi.12734

Roemer and Collins, Ibis 2020

**Comment by jfox590** [comment]
http://globalraptors.org/grin/researchers/uploads/222/collins_and_latta_2009.pdf 

Use this data

**Comment by jfox590** [comment]
Added Collins and Latta to Avian Diet Database
