### ISSUE TITLE
Finish Palermo 1971 for Black Francolin data 

### ISSUE THREAD

**Issue by jfox590** [hurlbertlab/dietdatabase#135]
Palermo, R. J. and G.   L. Doster. 1971. A comparison of the late winter foods and parasites of   Bobwhite Quail and Black Francolin in southwestern Louisiana. Proc. of the   24th Annual Conf. Southeastern Assoc. of Game & Fish Commissioners, Sept.   27-30 1970 (Webb, J. W., Ed.) Atlanta, GA.
--

**Comment by ahhurlbert** [comment]
Entered
