### ISSUE TITLE
clean prey names for Britto & Bugoni 2015, Roseate Spoonbill

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#142]
@mms726

Britto, V. O. and L.   Bugoni. 2015. The contrasting feeding ecology of great egrets and roseate   spoonbills in limnetic and estuarine colonies. Hydrobiologia 744:187-210.

Looks like the prey data from this study in AvianDietDatabase.txt have not yet been cleaned for prey names (there is no ITIS ID or Prey_Name_Status).

**Comment by mms726** [comment]
Done!
