### ISSUE TITLE
Enter data from Thompson 1973

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#144]
Thompson, D. 1973. Feeding ecology of diving ducks on Keokuk Pool, Mississippi River. Journal of Wildlife Management 37:367-381.

Currently we have entries from this paper in the database for American Coot (Table 6), and also for Ruddy Duck. 

The existing entries in our database for Ruddy Duck are from Table 3, but the Fraction_Diet values and Diet_Type are incorrect. The methods are not described well in this paper, but the values in the table are *numbers of gizzards*, not number of prey items, thus these are Occurrence data. The prey information is all fine, but Fraction_Diet values need to be re-entered for these records (directly from the Percent column).

It seems as though data for the other species in Table 3 have not yet been entered.

Table 4 can be ignored, as it simply breaks down the info in Table 3 by individual sites (that don't necessarily differ in habitat).

Table 7 includes data broken down by Fall 1966, Spring 1967, Fall 1967, Spring 1968. Data on Fall 1966 and Fall 1967 were combined in Table 3, so these do not need to be entered. But columns for Spring 1967 and Spring 1968 do need to be entered.

Table 8 also reports data from Spring 1968, and yet the %'s do not line up with those in Table 7. Some detailed reading is in order to figure out how these two datasets differ. It may be that they refer to the same birds, or that we cannot tell how they differ, in which case we WILL NOT enter the % Occurrence data from Table 8. HOWEVER, % by Items can be calculated from the first column of Table 8, and this is not given anywhere else in the paper.

NOTE for Table 8: Under prey items "S. striatinum" there is a breakdown provided by size (Large, Medium, Small) which can be ignored. Only enter the total, and be sure not to double count those values when tallying the total number of prey items. Under prey item "Chironomidae", all of the size categories can be lumped into one group with Prey_Stage = larva, and the Pupa will be entered separately. Again, don't double count these values as they are represented in the Table twice (by subcategory, as well as by the total for the category).

Be alert to other related issues in this paper that I may have missed.

**Comment by mms726** [comment]
The Ruddy Duck fraction diet data already in the database has been fixed, and the Lesser Scaup data from Table 3 has been entered as well.

**Comment by IREdwards27** [comment]
Data for the other species is now entered into a document but has not been cleaned yet. I'll clean it once I add the other data from the paper.

**Comment by IREdwards27** [comment]
The percent occurrence in Table 8 appears to be for a subset (134 ducks) of the sample from Table 7 (139 ducks for Spring 1968). The items should still be perfectly usable. I've now entered all of the data from Table 3 and Table 7.

**Comment by IREdwards27** [comment]
All data from the paper has been entered and just needs to be cleaned.

**Comment by IREdwards27** [comment]
All data from this paper has been entered and cleaned, the work I did just needs to be added to the main database file.
