### ISSUE TITLE
complete search for Parulidae diet data

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#148]
The following species in Parulidae are missing from the `NA_avian_diet_refs.txt` file and therefore may never have been intentionally searched:

Golden-winged warbler
Black-throated gray warbler
Yellow-throated warbler
Northern Parula*
Tropical Parula
Ovenbird*
Louisiana waterthrush*
Connecticut warbler*
Mourning warbler*
Canada warbler*

For each of the above species, 
1) go to https://birdsoftheworld.org/bow/home (subscription only, so you'll need to be connected to UNC's VPN), and visit the species' *Diet and Foraging* page.   
2) Look up each of the references cited on that page, and add them to the `NA_avian_diet_refs.txt` and indicate whether they do or do not have any quantitative diet data. Pay attention to whether any studies are cited within those papers that might potentially contain such data.   
3) On Google Scholar, put the following search terms in quotes: "[common name] AND (diet OR foraging OR food)", for example "golden-winged warbler AND (diet OR foraging OR food)". Follow up with any papers that have titles indicating they might contain quantitative data. Add all papers examined to the `NA_avian_diet_refs.txt` file regardless of whether they have data.
4) For species above with an *, some diet data exists currently in our Avian Diet Database. Be sure to check that any papers you find in your literature search are not already entered.

**Comment by ahhurlbert** [comment]
Note that "golden-winged warbler" has actually been listed as its own issue, so ignore that species here. Update in this issues thread as you finish searching a species on the list above.

**Comment by mms726** [comment]
Finished with Black-throated Gray Warbler
