### ISSUE TITLE
Problem with File Size? (refs)

### ISSUE THREAD

**Issue by seyfriedc** [hurlbertlab/dietdatabase#15]
@ahhurlbert Either a merge or something I did accidentally added thousands of columns to the Refs spreadsheet, so I removed the extra columns, saved the document without the columns, and tried to commit and push the changes. Git will not push because it says the file size is too large, but the file on my computer is not even close to being over 100 MB (the size limit).

**Comment by ahhurlbert** [comment]
@seyfriedc Try opening in Excel, and copying only the columns you want, and pasting into a new Excel document. Close the first one, and then Save As using the same file name, and see if it will push.

**Comment by seyfriedc** [comment]
Something must still be awry... I tried your advice above and I got the same "file size" message when trying to push my work today. The weird thing is that when I pull, it says my branch is up to date. I'll be in on Wednesday, so I can show/explain the problem more then if you're free. Thanks
