### ISSUE TITLE
Finish entering data in Jackson 2018

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#150]
Data on small heron diets available in "EFFECT OF DIET DIFFERENCES AND NON-NATIVE PREY CONSUMPTION ON
THE PRODUCTIVITY OF SMALL HERONS", Jackson 2018 (pdf in pdfs folder)

@mms726 could you finish this one you started? Looks like data are available in Tables 2.6 and 2.7.

**Comment by mms726** [comment]
Data needs to be shifted down one line at Orinoco sailfin catfish and again at sheepshead minnow--will finish once Plantae entries are gone through
