### ISSUE TITLE
diet data for thrush species

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#152]
Data from Beal 1915 "Food habits of the thrushes of the United States" has not yet been entered. (Not to be confused with Beal 1915 "Food of the robins and bluebirds")

https://babel.hathitrust.org/cgi/pt?id=hvd.32044106209406&view=1up&seq=3

In addition, there may be data in the Bent Life History of Birds accounts, but care should be taken that the information here is not simply re-summarizing data from Beal or other sources that might already be in the Diet Database.

https://babel.hathitrust.org/cgi/pt?id=uc1.31822009265877&view=1up&seq=11

**Comment by mms726** [comment]
All the data from that paper has been entered except Gray-cheeked and Bicknell's Thrushes. Beal combines these two species in his analysis, so I don't know that the data is usable for us but I wanted to make a note of it in case it is.

**Comment by ahhurlbert** [comment]
@mms726 Go ahead and enter it with common name "Gray-cheeked/Bicknell's Thrush" and scientific name "Catharus minimus/bicknelli"
