### ISSUE TITLE
consider adding Diet Database to GloBI Zenodo Community

### ISSUE THREAD

**Issue by jhpoelen** [hurlbertlab/dietdatabase#158]
If you'd like GloBI to only index released versions, please consider adding your zenodo publication to the GloBI community (globalbioticinteractions community) at https://zenodo.org/communities/globalbioticinteractions .

On getting added to the GloBI Zenodo community, GloBI will no longer index the latest and greatest from github, but only the most recent released versioned on Zenodo.

**Comment by jhpoelen** [comment]
Just checked, and for some reason, I did not get a request for your publication to be added to the Zenodo Global Biotic Interactions community. 

at https://zenodo.org/record/5557741 I expected the GloBI community to show up in the little side panel . . . however, I saw (see attached screenshot).

![Screenshot from 2021-10-13 16-47-14](https://user-images.githubusercontent.com/1084872/137227852-7cdfa07b-e76c-470c-9179-4acb8d21f8a8.png)

For example of pubs part of the GloBI community, see e.g.:

Cristina Preda, & Quentin Groom. (2021). Vespa velutina interactions from literature (v1.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.5501763

with side panel that looks like (see attached) 

![Screenshot from 2021-10-13 16-51-22](https://user-images.githubusercontent.com/1084872/137228116-ebfecc86-43ca-4d0f-b22d-f7d126550fe8.png)

**Comment by ahhurlbert** [comment]
When I go to edit the record I see the Global Biotic Interactions block icon under Communities like this:
![image](https://user-images.githubusercontent.com/2699790/137229959-f6b24616-e233-4b6c-95c4-4462d01e9987.png)

Then I hit Publish. I still don't see it in my side panel, but maybe it just takes a bit?

**Comment by jhpoelen** [comment]
After you did this, I received an email:

```
A new upload requests to be added to your community (Global Biotic Interactions):


Record Title: hurlbertlab/dietdatabase: v.1.0.7
Record Description: Updating the database in which several records with errors in Fraction_Diet have been corrected or deleted. Several Sources listing different sets of page numbers were merged together which is why the number of studies has decreased. Current release has 73,049 records for 759 species and 986 studies.

You can accept or reject this record in your community curation page:
https://zenodo.org/communities/globalbioticinteractions/curate/
```

And after I click accept, your pub should be in the community (See attached screenshot)

![Screenshot from 2021-10-13 17-50-20](https://user-images.githubusercontent.com/1084872/137232238-9fd02419-99b7-41e1-bb50-cf6ad68d25a5.png)


Please confirm by closing this issue..
