### ISSUE TITLE
Storer

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#18]
Storer, R. W. 1966. Sexual dimorphism and food habits of three North American accipiters. Auk 83:423-436.

@seyfriedc In this study you recorded the Taxonomic authority as the AOU 5th ed instead of 7th ed. Not sure if this was a typo, or if you did this because the study reported using the 5th ed.

We want to make sure that if we have an older paper using out of date names that we convert those names to whatever is most appropriate at the time the data is entered. For right now, this will be the 7th ed., 54th supplement. Make sure the names are up to date in Avibase, change the Taxonomy field, and correct names if necessary.

Thanks!

**Comment by seyfriedc** [comment]
Yes, that was a mistake for the Cooper's Hawk and Common Black-Hawk studies. I changed and updated the file.
