### ISSUE TITLE
Corvidae refs duplicated by merge

### ISSUE THREAD

**Issue by seyfriedc** [hurlbertlab/dietdatabase#20]
After I merged today I noticed that the Corvidae refs now have many small duplicated sections. I wasn't sure which sections were best to keep. 

@Lexiep I think you've been working on Corvidae, could you take a look?

**Comment by ahhurlbert** [comment]
I fixed it for now, but @lexiep should probably stop by my office the next time she comes in just to review what's going on. Thanks.

**Comment by Lexiep** [comment]
So sorry about this, Allen! I’ll be by around 4 tomorrow.

--
Lexie Peeler
Undergraduate Student
BS Environmental Science, Marine Science minor
University of North Carolina at Chapel Hill
