### ISSUE TITLE
Bald eagle diet info

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#21]
There's a new 2015 study with diet data for two island groups here:

Newsome SD, Collins PW, Sharpe P. Foraging ecology of a reintroduced population of breeding Bald Eagles on the Channel Islands, California, USA, inferred from prey remains and stable isotope analysis. The Condor [Internet]. Cooper Ornithological Society; 2015 Jul 22;117(3):396–413. Available from: http://dx.doi.org/10.1650/condor-14-213.1

**Comment by pwinner1** [comment]
entered
