### ISSUE TITLE
Incomplete entry of data from Aldous 1942

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#22]
Aldous, S. E. 1942. The White-necked Raven in relation to agriculture. Res. Rep. 5. U.S. Fish Wildl. Serv.

Data are provided for all 12 months separately, but only October and May-June are entered (why are May-June combined?). All of these entered data for the Chihuahuan Raven need to be double-checked, and diet data for all of the remaining months still needs to be entered.

**Comment by pwinner1** [comment]
entered
