### ISSUE TITLE
missing references lines 5350 - 5431

### ISSUE THREAD

**Issue by jhpoelen** [hurlbertlab/dietdatabase#24]
I noticed that lines  5350 - 5431 in https://github.com/hurlbertlab/dietdatabase/blob/5964598c9690065cbf4d83b7309a8b16394f996d/AvianDietDatabase.txt do not have a reference. I am assuming that associating a reference to a record is not optional.

Hope this helps,
-jorrit

**Comment by ahhurlbert** [comment]
Thanks for pointing that out. Refs have been added. Happy new year!
