### ISSUE TITLE
suspicious sequence of references to Platt, J.B. 1971. A SURVEY OF NESTING HAWKS, EAGLES, FALCONS AND OWLS IN CURLEW VALLEY, UTAH. Great Basin Nat. 31:51-100

### ISSUE THREAD

**Issue by jhpoelen** [hurlbertlab/dietdatabase#26]
From http://www.globalbioticinteractions.org/references.html , I noticed a suspicious sequence of references to Platt, J.B. 1971. A SURVEY OF NESTING HAWKS, EAGLES, FALCONS AND OWLS IN CURLEW VALLEY, UTAH. Great Basin Nat. 31:51-10* .  (see screenshot below).

Suspect copy/paste artifact from excel.

![screen shot 2016-03-29 at 8 37 40 pm](https://cloud.githubusercontent.com/assets/1084872/14131279/902ae886-f5ee-11e5-833a-dc066c456612.png)

**Comment by ahhurlbert** [comment]
Thanks @jhpoelen. It's been fixed.
