### ISSUE TITLE
Louisiana waterthrush data

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#27]
http://www.aoucospubs.org/doi/full/10.1642/AUK-15-222.1?utm_source=May+2016+Content+Alert&utm_campaign=May+2016+Content+Alert&utm_medium=email

**Comment by meganblawas** [comment]
I'm having trouble finding the paper with this link, is there a title I can search for?

**Comment by ahhurlbert** [comment]
Oops, sorry. I think it's this one:

http://www.americanornithologypubs.org/doi/full/10.1642/AUK-15-222.1

Go ahead and save to Papers with Data folder too.

**Comment by pwinner1** [comment]
entered

**Comment by ahhurlbert** [comment]
Data has been entered for diet items identified to the species level from DNA barcoding (Table 1).

Please also enter seasonal summaries for the 6 orders in Figure 2 (ignore "Other terrestrial") at the two sites. You'll have to measure and convert bar heights from the figure.

**Comment by pwinner1** [comment]
entered
