### ISSUE TITLE
Beal 1898- Yellow and black billed cuckoos

### ISSUE THREAD

**Issue by savannahswinea** [hurlbertlab/dietdatabase#30]
Study by Beal in 1898 combines diet by occurrence data for yellow and black billed cuckoos.

**Comment by ahhurlbert** [comment]
Entered as Yellow-billed/Black-billed Cuckoo and Coccyzus sp. At the moment, this is entered as % Unspecified although reading of the text make it likely that it should be % by Volume.

There is also information on % occurrence that remains to be added.

**Comment by ahhurlbert** [comment]
Data has been entered.
