### ISSUE TITLE
fixing capitalization in Habitat_type and other fields

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#38]
To make ALL letters in a text string lower case in R, use the function `tolower` like this:

diet$Habitat_type = tolower(diet$Habitat_type)

**Comment by ahhurlbert** [comment]
@pwinner1 Have we standardized capitalization in all of the necessary fields in the database? I think this issue was just a reminder to myself to do that, so if it's done you can go ahead and close the issue.

**Comment by pwinner1** [comment]
I believe we have. I know I used this function on certain fields and made corrections to other fields where the text was not all lowercase, such as how we decided to standardize season with the first letter capitalized.
