### ISSUE TITLE
The Notes field

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#4]
@mauriemma @msandova @jsbarnes @seyfriedc @wlarsen2 @Lexiep 
The notes field is for describing any unusual ways the study was conducted or ways that the data was manipulated to convert from raw data in the paper to the data entered in our database.

For the sparrow study, we might want to have a note that said something like "Converted %s of arthropod diet and %s of plant diet to % of total diet using total number of plant and arthropod diet items". 

@seyfriedc Can you find the relevant rows for this study in the Avian_Diet_Database.txt file and paste this into every row related to this study?

Close this issue when you've finished!

**Comment by seyfriedc** [comment]
Yes, I added the comment to every cell in the "notes" column for the Allaire and Fisher sparrow study.
