### ISSUE TITLE
enable https://travis-ci.org/hurlbertlab/dietdatabase for automated checks by GloBI

### ISSUE THREAD

**Issue by jhpoelen** [hurlbertlab/dietdatabase#40]
Now that you have accepted https://github.com/hurlbertlab/dietdatabase/pull/39 and a ```.travis.yml``` has been  added to the repository, the last step to enable automated checks by GloBI (or whenever you configure in ```.travis.yml```) is to go to https://travis-ci.org/hurlbertlab/dietdatabase, login using your github account and enable the repository.

**Comment by ahhurlbert** [comment]
Tried, but not sure it worked. Let me know if I need to try again.

**Comment by jhpoelen** [comment]
From what I can tell, it looks like you've activated the project! You should now be able to trigger a "build" by making a change to the repository. I usually add a space to the README.md or make some other minor change to trigger the process.

**Comment by ahhurlbert** [comment]
Ok, add a space as suggested to README.md, and build failed.

But I'm assuming this is due to the original issue that prompted you to create this issue, which is that we slightly restructured the database such that before we had 4 separate columns with "Fraction_Diet" info (Fraction_Diet_By_Wt_or_Vol, Fraction_Diet_By_Items, Fraction_Diet_Occurrence, and Fraction_Diet_Unspecified) and now we have a single quantitative field for "Fraction_Diet" and a second field for "Diet_Type" that describes the method by which the fraction is calculated.

**Comment by jhpoelen** [comment]
Great that the build is failing. It made me realize that the globi checker does not yet support your dataset /database, because your data is discoverable in GloBI (see http://globalbioticinteractions.org/status). So, in short, the problem is on my end.

Here's what I'll do:

1. create pull request to add ```globi.json```. This file is used by GloBI to auto-discover your data and tell is where to look and how to read it. Currently, I've hardcoded the configuration meaning that if you move or rename the repository, the integration will fail. With the auto-discover, you can also decide to no longer share the data by simply removing /renaming the globi.json file.

1. create a new version of the globi github checker tool that includes support for your database format. 

Thanks for your patience.

**Comment by jhpoelen** [comment]
I've completed 1) and 2). 

Note that on each pull request, travis will also run. For my outstanding pull request, the travis run will fail, but hopefully for future runs, it'll provide an additional check prior to merging a pull request. (see attached screenshot for example of pull request + pending travis check).

![automated-check-on-merge](https://cloud.githubusercontent.com/assets/1084872/22128876/a7c19600-de57-11e6-88a2-74f46e6ae581.png)

**Comment by jhpoelen** [comment]
travis integration has been enabled, new issue on the false negative results is reported here: https://github.com/jhpoelen/eol-globi-data/issues/276 .
