### ISSUE TITLE
name correction suggestion for [Myctera americana]

### ISSUE THREAD

**Issue by jhpoelen** [hurlbertlab/dietdatabase#44]
Hi!
I found a taxon name ```Myctera americana``` at a [globi page](http://globalbioticinteractions.org/?accordingTo=globi%3Ahurlbertlab%2Fdietdatabase&interactionType=interactsWith&sourceTaxon=no%3Amatch). After reviewing the data sources and relevant taxonomic tools like the [globalnames resolver](http://resolver.globalnames.org), I think that suggestion below might be helpful.

 Thanks!

| name | suggested name | name url reference | notes
| --- | --- | --- | ---
| Myctera americana | Mycteria americana | http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=174897 | some notes

@ahhurlbert I've made a little widget that create an issue template (see above) after following status page > click on name match percentage > click on "suggest correction" . Useful?

**Comment by ahhurlbert** [comment]
If I understand you correctly, the widget will automatically post a new issue for each problematic name that is identified?

But I don't understand what you're referring to with "status page", and hence the subsequent link trail (the 'globi page' linked to above does not work, is that what you mean?).

So perhaps this could be quite useful but I need some clarification.

At the moment, our current workflow is to get the file of unmatched names from GloBI where the suggested names are also listed. See instructions [here](https://github.com/hurlbertlab/dietdatabase/blob/master/cleaning/name_cleaning_instructions.md). We're just a little behind, but all names will get cleaned eventually!

**Comment by jhpoelen** [comment]
I think I was a little too quick to share this idea with you. First, I corrected to link to the "globi page" (also [here](http://www.globalbioticinteractions.org/?accordingTo=globi%3Ahurlbertlab%2Fdietdatabase&interactionType=interactsWith&sourceTaxon=no%3Amatch)).

Second, the semi-automated workflow would be something like:

1. user goes to the status page at http://globalbioticinteractions.org/status
2. user locates dataset of interest (e.g. 
![screenshot from 2017-02-10 15-21-05](https://cloud.githubusercontent.com/assets/1084872/22847936/7b8f232c-efa5-11e6-90f1-53a99fca2b33.png)) 
3. user now click on the name match percentage (e.g. 
![screenshot from 2017-02-10 15-14-38](https://cloud.githubusercontent.com/assets/1084872/22847941/8e01b6c8-efa5-11e6-8653-854672177fb0.png)) 
4. now, [a page](http://www.globalbioticinteractions.org/?accordingTo=globi%3Ahurlbertlab%2Fdietdatabase&interactionType=interactsWith&sourceTaxon=no%3Amatch) is loaded that shows records with unmatched names for the specific dataset (see 
![screenshot from 2017-02-10 15-17-34](https://cloud.githubusercontent.com/assets/1084872/22847956/b3cd6528-efa5-11e6-9889-8da0526bc17d.png))
5. for each unmatched name a ["suggest correction" link](https://github.com/hurlbertlab/dietdatabase/issues/new?body=Hi%21%0AI%20found%20a%20taxon%20name%20%60%60%60Myctera%20americana%60%60%60%20on%20a%20%5Bglobi%20page%5D%28http%3A%2F%2Fwww.globalbioticinteractions.org%2F%3FaccordingTo%3Dglobi%253Ahurlbertlab%252Fdietdatabase%26interactionType%3DinteractsWith%26sourceTaxon%3Dno%253Amatch%29.%20After%20reviewing%20the%20data%20sources%20and%20relevant%20taxonomic%20tools%20like%20the%20%5Bglobalnames%20resolver%5D%28http%3A%2F%2Fresolver.globalnames.org%29%2C%20I%20think%20that%20suggestion%20below%20might%20be%20helpful.%0A%0A%20Thanks%21%0A%0A%7C%20name%20%7C%20suggested%20name%20%7C%20name%20url%20reference%20%7C%20notes%0A%7C%20---%20%7C%20---%20%7C%20---%20%7C%20---%0A%7C%20Myctera%20americana%20%7C%20YOUR%20SUGGESTED%20NAME%20%7C%20http%3A%2F%2Fsomereference%20%7C%20some%20notes&title=name%20correction%20suggestion%20for%20%5BMyctera%20americana%5D) is visible
6. after clicking on the "suggestion correction" link, a pre-populated github issue is shown (see 
![screenshot from 2017-02-10 15-32-28](https://cloud.githubusercontent.com/assets/1084872/22848017/2ff48802-efa6-11e6-9c50-ffa04c16ba02.png))
7. user now fills in the generated template and creates the issue. 

So, this work flow is semi-automatic and is designed to help folks make suggestion to the curators of a source dataset (in this case the dataset at https://github.com/hurlbertlab/dietdatabase).

Please let me know if this description is clear and whether it would help you with name curation.

Thanks for being patient!

**Comment by ahhurlbert** [comment]
This seems useful, however it seems you have already written code to suggest a specific name (as you list in the taxonUnmatched.tsv file), so perhaps you could autofill this suggestion in the issue text when available?

Of course, it is incumbent on the reviewer to verify this suggestion, but it saves them several steps not having to start from scratch.

**Comment by ahhurlbert** [comment]
I finally embraced programmatic name cleaning in our own way using R's taxize package. Waiting until the database gets a little more stable before running it, but we will soon be primarily ITIS-conforming (see comments under #48 for more details).
