### ISSUE TITLE
Append Olsen's database lines to ours

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#45]
@aaronolsen We're now ready for you to append your (now cleaned) NewDietDatabaseLines.txt to the end of our AvianDietDatabase.txt file.

**Comment by aaronolsen** [comment]
I pulled down the current version, added the new lines from the dietdatabase folder, and committed the new version through the browser using "Upload files". The commit is showing up in the history and I'm also seeing the new lines on my github desktop clone. But the new lines are not in the AvianDietDatabase.txt when I download it, and there seems to be some "Travis CI" error in the the commit history for the file. Do you know what I'm doing wrong?

**Comment by jhpoelen** [comment]
(apologies for chiming in)... it seems like line 21148 of the AvianDietDatabase contains header names. This is what is causing the travis check to fail.

Snippet from AvianDietDatabase.csv prefixed with line numbers:
 
```tsv
...
21147 Warbling Vireo  Vireo gilvus    Vireonidae  "AOU 7th ed., 54th supplement"        -116.0833333  43.6  NA  1845  NA  Idaho Lucky Peak  coniferous forest; s      hrubland  NA  2000  NA  2003  Fall  Plantae         Rhopalidae        veri      fied    fruit   0.736 Occurrence  53  NA  NA  stomach contents      "Carli      sle, et al. 2012. Food Availability, Foraging Behavior, and Diet of Autumn       Migrant Landbirds in the Boise Foothills of Southwestern Idaho. The Condo      r 114(3):449-461"
21148 Common_Name Scientific_Name Subspecies  Family  Taxonomy  Longitude_dd  La      titude_dd Altitude_min_m  Altitude_mean_m Altitude_max_m  Location_Region       Location_Specific Habitat_type  Observation_Month_Begin Observation_Year_B      egin  Observation_Month_End Observation_Year_End  Observation_Season  Prey      _Kingdom  Prey_Phylum Prey_Class  Prey_Order  Prey_Suborder Prey_Family Pr      ey_Genus  Prey_Scientific_Name  Unidentified  Prey_Name_Status  Prey_Stage        Prey_Part Prey_Common_Name  Fraction_Diet Diet_Type Item_Sample_Size  Bi      rd_Sample_Size  Sites Study_Type  Notes Entered_By  Source
21149 Wood Duck Aix sponsa  NA  Anatidae  eBird Clements Checklist v2016  NA  NA        NA  NA  NA  South Carolina  NA  NA  10  NA  2 NA  NA  Viridiplantae Stre      ptophyta  Liliopsida  Commelinales  NA  Commelinaceae Aneilema  NA  NA  NA        NA  seed  NA  0.233 Wt_or_Vol 24  103 NA  stomach contents  NA  AMO "Lan      ders, J.L., Fendley, T.T. & Johnson, A.S. (1977) Feeding ecology of wood d      ucks in South Carolina. Journal of Wildlife Management, 41, 118–127."
...
```

**Comment by aaronolsen** [comment]
Thanks Jorrit. It ultimately ended up merging so I removed that line from the current AvianDietDatabase.txt file. I also deleted the previous temp file (NewDietDatabaseLines.txt). Let me know if there's anything else I can do.

**Comment by jhpoelen** [comment]
Happy to help... looks like you fixed the Travis CI check. Nice!

**Comment by ahhurlbert** [comment]
Great! Thanks all!
