### ISSUE TITLE
wrong families in hundreds of entries?

### ISSUE THREAD

**Issue by pwinner1** [hurlbertlab/dietdatabase#46]
A large number of familes for prey items appear to be wrong, starting from at least about row 5700 onwards to the end of the original database.

Don't have time to post an example, but they should be easily spotted.

**Comment by ahhurlbert** [comment]
Looks like Prey_Family column was accidentally shifted down by 11 rows starting at line 5696, but that the surrounding fields were unaffected.

This happened prior to the merging of the Olsen database lines, and so there were several records from row 21141 on that were just a bunch of NAs except for values in the Prey_Family field.

All Prey_Family values from 5696 to 21146 were shifted upwards and now everything looks to be aligned correctly.
