### ISSUE TITLE
Correct values using PreySummary of Diet Type 

### ISSUE THREAD

**Issue by pwinner1** [hurlbertlab/dietdatabase#47]
Here are the correct values for the Acorn Woodpecker:

Unspecified	Unid. Plantae	0.846666667
Unspecified	Hymenoptera	0.087666667
Unspecified	Coleoptera	0.034
Unspecified	Unid. Insecta	0.030666667

**Comment by ahhurlbert** [comment]
Ok, I've modified the preySummary function and it now returns these values.
