### ISSUE TITLE
Bird Sample Size as a grouping/selecting field for multiple entries in a study

### ISSUE THREAD

**Issue by pwinner1** [hurlbertlab/dietdatabase#49]
In addition to the existing defined fields, Bird Sample Size should probably be added to group/select? entries of a study so that the preySummary values are correctly representing the averages across multiple entries of studies.

In the instance of the American Tree Sparrow, all fields that would normally distinguish different groupings of data are the same except for Bird Sample Size. This happened because there is data from the same study for the time period July 1 - 15 and then July 16 - 31 (so same month and year) in the same location and habitat.

**Comment by ahhurlbert** [comment]
Try this now with the new preySummary function. If it works, go ahead and close the issue.

**Comment by pwinner1** [comment]
Everything seems to be working properly now. Closing.
