### ISSUE TITLE
autumn migration diet data for entry

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#50]
Parrish. 1997. Patterns of frugivory and energetic condition in Nearctic landbirds during autumn migration. Condor 99: 681-697.

https://sora.unm.edu/sites/default/files/journals/condor/v099n03/p0681-p0697.pdf

**Comment by ahhurlbert** [comment]
@meganblawas Megan, I think you said you finished entering this paper. If that's correct, can you go ahead and close this issue?

**Comment by meganblawas** [comment]
Yes that's correct!
