### ISSUE TITLE
kingbird diet data

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#51]
Data to be entered for Cassin's Kingbird and Western Kingbird from

Ohlendorf, H. M. 1974. Competitive relationships among kingbirds (Tyrannus) in trans-Pecos Texas. Wilson Bull. 86:357-373.

which is in the Papers With Data folder.

Data to be entered is from Figures 5-7 (you'll have to estimate to the nearest % based on the bar lengths).

Figure 5 (occurrence data) has already been entered for Cassin's Kingbird (Tyrannus vociferans) but not Western. Neither species has diet data from Figures 6 (% items) and 7 (% volume) entered.

This means you can just copy the previously entered records (which currently start around row 19820), and paste a new set of rows (since it will be the same 9 diet items each time) just modifying the % values and the Diet_Type info each time.

**Comment by ahhurlbert** [comment]
NOTE PREY TAXONOMY CHANGES:

"Homoptera" is now recorded as Hemiptera | Auchenorrhyncha | Cicadidae (since they specified in the text and table that these are cicadas.

"Hemiptera" is now recorded as Hemiptera | Heteroptera

**Comment by pwinner1** [comment]
Now entered
