### ISSUE TITLE
Incomplete data entry of Rosenberg et al. 1982

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#52]
Rosenberg, Ohmart and Anderson. 1982. Auk 99: 260-274 has diet data in Figure 6 for 13 bird species broken down both by volume and by number items.

Easiest thing may be to print out a large version of this figure and use a ruler to record all of the bar segment lengths in mm. Then you can convert them all simultaneously to %s using a conversion based on the length of the bar from 0-100%.

At the moment, only Brown-crested Flycatcher and Scarlet Tanager have been entered (partially). These values should be re-checked.

**Comment by pwinner1** [comment]
entered
