### ISSUE TITLE
Location_Region needs cleaning

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#56]
count(diet, Location_Region) %>% arrange(desc(n)) %>% data.frame()

shows that there are various locations that should be moved to Location_Specific.

Location_Region will typically be a country or state name.

Note also that there are 4402 records where Location_Region is NA, and 317 where it is blank. These should be filled in.

For studies where the data clearly come from multiple places around the country (e.g. Beal compendia), we have been specifying "Multiple".

**Comment by pwinner1** [comment]
finished cleaning location_region
