### ISSUE TITLE
re-enter Cedar Waxwing data from Witmer 1996

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#57]
Paper is in Papers with Data folder, or here: 

https://sora.unm.edu/sites/default/files/journals/auk/v113n02/p0414-p0430.pdf

@pwinner1 entered some records for this paper, but I can't see where those data came from (currently records 5348-5365), and they also seem incomplete.

Data are in Fig 2 (% by volume), and should be entered separately for each month. Don't forget to include % flowers from Fig 1 and % Insecta as the difference between 100% and the top of the bars in Fig 1. Will probably be useful to print out these Figures and measure with ruler (or paste fig into Powerpoint and measure with box tool, etc).

Arthropod occurrence data are given in Table 3.

**Comment by pwinner1** [comment]
deleted incorrect records that I had previously entered and entered new data from Figs 1,2,3
