### ISSUE TITLE
Unspecified fraction diet

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#58]
The diet data from Beal compendia are never explicit about what fraction of diet is being reported (% Items or % Wt_or_Vol).

The introduction to Wheelwright 1986 discusses U.S. Biological Survey Records and Beal data, and implies that these records are all % by volume.

Thus we should change "Unspecified" to "Wt_or_Vol" for all Beal studies.

**Comment by ahhurlbert** [comment]
To clarify, some of the data Beal reports are clearly % Occurrence, and these should not be changed.

But Unspecified should be changed, and records where Diet_Type is "Items" should be re-examined as that may have been a guess that also be changed to "Wt_or_Vol".

**Comment by ahhurlbert** [comment]
Maybe since @thenness is checking Beal papers for duplicates he can keep an eye out for any language that might confirm that some of the diet data is % by Items. If no such language is found, then I think we convert at "Items" in Beal studies to "Wt_or_Vol".

**Comment by thenness** [comment]
Agreed.  Other than when the papers are clear about occurrence data, there's no indication that any different method is being used so I've been changing the Items and Unspecified entries to Wt_or_Vol as I go.  I believe I have almost all the Beal entries edited this way, will double check.
