### ISSUE TITLE
enter data from Earhart & Johnson 1970

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#65]
Data on % occurrence for screech owl (separate subspecies; check that these line up with Eastern Screech Owl and Western Screech Owl)  and Pygmy Owl (now Northern Pygmy Owl?, with separate data for males vs females) in Tables 4 and 5.

Paper here and in Papers with Data folder:
http://www.jstor.org/stable/1366002?seq=1#page_scan_tab_contents

**Comment by pwinner1** [comment]
All 3 subspecies seem to be referring to the Western Screech owl, so unless I'm mistaken, I will combine all the subspecies, but still separate by male/female diets

**Comment by pwinner1** [comment]
entered
