### ISSUE TITLE
Study_Type cleaning

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#66]
`table(diet$Study_Type)` will show the frequency of all phrases in this field.

We need to clean this field up and use consistent terminology. Multiple types may be specified by separating with a ";", but the types themselves should be constrained to the following options:

* behavioral observation (not "observed", "observation", "observational", "direct observation", "field observation", "nest observation", "observatioin of prey", etc)
* crop contents (not "crop")
* emetic
* esophagus contents (not "esophogeal contents", "esophagi", "throat contents", "nestling throat contents", "gullet contents", "throat collar", "nestling throat collar", etc)
* fecal contents (not "fecal examination")
* nest debris (not "nest contents"
* pellet contents (not "castings", "pellet analysis", "pellets", "fecal pellet analysis", etc)
* prey remains (not "remains analysis")
* stomach contents (not "nestling stomach contents", "gizzard contents", "gizzard analysis", "stomach", etc)

Phrases to delete:
"tagged"
"estimation"

Note that there are 18 records with no Study_Type value and 63 records with NA, so we need to look those up and fill in.

**Comment by pwinner1** [comment]
finished cleaning Study_Type
