### ISSUE TITLE
References cleaning

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#67]
* Verify that all references are in the following exact format:

Lastname, Initials (followed by .'s), Initials Lastname, Initials, Lastname, and Initials Lastname. Year. Article title. Journalname all spelled out (no abbreviations) Volume_number: page-pages.

It may be useful to do find and replace of abbreviated journal names to fix many at once.

* Note that Olsen db references (mainly ducks and geese) put parentheses around the year like this:

Hohman, W.L. (1985) Feeding ecology of ring-necked ducks in northwestern Minnesota. Journal of
  Wildlife Management, 49, 546-557.

You could try selecting many cells of the Reference column at once and Find+Replace "(" for "", and then ")" for ".".  But, be very careful as some article titles may have parentheses that you don't want to get rid of.

* Some titles are in all caps and need fixing, e.g. like this: 

Platt, J.B. 1971. A SURVEY OF NESTING HAWKS, EAGLES, FALCONS AND OWLS IN CURLEW VALLEY, UTAH. Great Basin Nat. 31:51-65

* In some cases, author names with special characters (like accents or tildes) will have gotten converted to ?s like this:

Jaksic, F. M., H.  W. Greene, and J. L. Ya????ez. 1981. The guild structure of a community of
  predatory vertebrates in central Chile. Oecologia 49:21-28.

Look up the study and fix the name.

* Some references are incomplete like this:

Haag, K. R., J. C. Joyce, W. M. Hetrick, and J. C. Jordan. 1987. Predation on waterhyacinth weevils and other aquatic insects by three wetland birds in Florida. Fla.

**Comment by pwinner1** [comment]
finished
