### ISSUE TITLE
cleaning the Prey_Stage field

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#76]
(fledgling, nestling, young, fawn, ducklings, immature, parr, smolts, suckling) --> juvenile
(larvae, larval, naiads) --> larva
(pupae, cocoon) --> pupa
(eggs, ephippia) --> egg

**Comment by ahhurlbert** [comment]
Note there is one instance where Prey_Stage is 'seed', but for this record 'seed' should be assigned to Prey_Part, not Prey_Stage

**Comment by pwinner1** [comment]
done
