### ISSUE TITLE
filling in Prey_Stage for Lepidoptera prey

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#77]
There are 528 records where prey is Lepidoptera but Prey_Stage is blank or NA.

We would really like to be able to distinguish 'adult' vs 'larva' for these, which will require looking in the original source.

Here are the records to examine:
```
lep_unk_stage = diet %>% 
  mutate(row = row.names(diet), source2 = substr(Source, 1, 30)) %>% 
  filter(Prey_Order == "Lepidoptera", Prey_Stage == "" | is.na(Prey_Stage)) %>% 
  select(row, Common_Name, source2)
```

**Comment by ahhurlbert** [comment]
Change Prey_Stage from "larvae; adult" to just "larva" for Carolina Chickadee.
Add one record for that study for Lepidoptera adult where Occurrence = 0.005 (1 out of 210 stomachs)

**Comment by pwinner1** [comment]
finished, changed all NA to blank
