### ISSUE TITLE
enter diet data from Cooper 1988 dissertation

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#79]
"Dietary relationships among insectivorous birds of an eastern deciduous forest"

Extract data from Figs 1, 3, 5, 7, 9, 11, 13, 16

(% by number of items)

Details in text

PDF in "Papers with data" folder

**Comment by pwinner1** [comment]
Checking the database, this hasn't been entered. I'll go ahead and enter it

**Comment by pwinner1** [comment]
entered
