### ISSUE TITLE
QA/QC observation month begin/end problem

### ISSUE THREAD

**Issue by pwinner1** [hurlbertlab/dietdatabase#84]
qa_qc() function does not detect when a value is not a numerical value when it should be. 

For example, "June" in observation month begin or end returning "OK" instead of pointing out the problem that it's not a numerical value.

**Comment by ahhurlbert** [comment]
Fixed. qa_qc() now tells you if 1) all values in a field are NA, 2) values in a numeric field are not actually numeric or integers, and 3) lists problematic record numbers if any.
