### ISSUE TITLE
California Quail in Hawaii - Useful?

### ISSUE THREAD

**Issue by aricha34** [hurlbertlab/dietdatabase#88]
http://www.jstor.org/stable/pdf/4080767.pdf?refreqid=excelsior:3a119afac54182f49eb2fda9a9a4e7ea

I found a paper with data for the California Quail from a study conducted over multiple islands of Hawaii. Would this paper still be considered relevant to North American species? Also, if it is, what would be the best way to go about handling the issue of the multiple vegetation zones. It seems that this paper references one study, but there are 10 vegetation zones- each with their own bird samples and quantitative diet data. Given that these data sets are separate from one another, what would be the best way to distinguish them within the Avian Diet Database Template?

**Comment by ahhurlbert** [comment]
Since this study is about diet of the species outside their native range, I think we can ignore it for our purposes.
