### ISSUE TITLE
the "Unidentified" field

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#9]
@wlarsen2 As a reminder, the "Unidentified" field is for when only a subset of the taxonomic level that prey is being classified as is unidentified.

In the Mosher & Matray 1974 study on Broad-winged hawks, part of the diet is listed as "Birds". While the particular bird species eaten were not identified, the fraction of the diet reported corresponds to ALL birds, and so the value in the "Unidentified" field should be NO.

Only if one or more diet items were birds that were identified down to some lower level (family, species) in addition to an all-encompassing "Other birds" category would the latter get categorized with an "Unidentified" value of YES.

Please check back over the YES values in this study and other recent ones you've been working on to make sure this is the spirit in which the "Unidentified" field is being filled out. Thanks!

**Comment by seyfriedc** [comment]
I'm fairly sure I entered the Mosher 1974 study, so I will fix this when I come in later today (3/6). I understand the issue/fix and I'll let you know if I have any questions.

**Comment by ahhurlbert** [comment]
Great, thanks! And go ahead and close the issue once you’ve taken care of it!
