### ISSUE TITLE
suggestion regarding usage of values like "unverified" in Prey_Name_ITIS_ID column

### ISSUE THREAD

**Issue by jhpoelen** [hurlbertlab/dietdatabase#90]
Currently, AvianDietDatabase.txt contains a column called ```Prey_Name_ITIS_ID```. GloBI expected the column to be only used to capture ITIS ids related to prey names. However, while chasing down some naming bug related to domestic chickens, I found that the value ```unverified``` is used in the column to document that the name needs attention.

I'll make a special check in GloBI to make sure that ```Prey_Name_ITIS_ID``` contains a number to filter out values like ```unverified```. However, I would urge you to create a separate column to capture the curation state of the prey name in order to reduce confusion among future contributors and users. 

Would it be an idea to resurrect the previously used ```Prey_Name_Status``` and insert this as a column next to the ```Prey_Name_ITIS_ID``` column?

**Comment by jhpoelen** [comment]
related to issue https://github.com/jhpoelen/eol-globi-data/issues/327 .

**Comment by ahhurlbert** [comment]
`Prey_Name_ITIS_ID` is now numeric only, and the `Prey_Name_Status` field was resurrected as suggested, which takes on values of "verified" if a valid ITIS ID was found, "accepted" if no valid ITIS ID was found but someone has looked into the taxonomic entity and decided it represents a potentially valid concept that is missing from or classified differently in ITIS, and "unverified" if no valid ITIS ID was found and no one has looked into it yet.

**Comment by jhpoelen** [comment]
Thanks!
