### ISSUE TITLE
Question about DDT in prey affecting prey diet

### ISSUE THREAD

**Issue by Dryu0003** [hurlbertlab/dietdatabase#94]
So one of the papers I am working with documents how DDE accumulation from prey affects the peregrine falcons in aleutian island, Alaska from 1968-1972. I know it was mentioned before that we will try to avoid the contaminated prey information if possible but for this paper there isn't any data concerning prey diet of pre-DDT of peregrine falcons. What should we do with prey diet information tainted by pesticides moving forward?

**Comment by ahhurlbert** [comment]
There is no problem with entering diet data from an area where pesticides are known to have been applied. You can mention the presence of pesticides in the Notes field.

**Comment by Dryu0003** [comment]
Acknowledged!


-------- Original message --------
