### ISSUE TITLE
Vireo diet data in Chapin 1925

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/dietdatabase#96]
Table 1: all but REVI, BHVI, and BWVI need to be entered (fraction by Wt_or_Vol)

Table 2: all needs to be entered (% Occurrence)
[Chapin 1925.pdf](https://github.com/hurlbertlab/dietdatabase/files/1605522/Chapin.1925.pdf)

**Comment by pwinner1** [comment]
Table 1 has been entered and is in the cleaning folder. Will continue on Table 2 Friday unless someone else wants to take over it.

**Comment by pwinner1** [comment]
Finished entering data
